spring:
  statemachine:
    data: 
      jpa:
        repositories:
          enabled: false
  datasource:
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      connectionTimeout: 30000
      maxLifetime: 500000
    url: ${DB_JDBC_URL:jdbc:postgresql://127.0.0.1:6432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
  jpa:
    database-platform: com.example.state.AppPostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true  